client:
  tcp1_dial_addr: 192.168.58.20
  tcp1_dial_port: 31420
  tcp1_conn_addr: 10.60.0.1
  tcp1_conn_port: 31421
  tcp2_dial_addr: 192.168.59.20
  tcp2_dial_port: 31422
  tcp2_conn_addr: 10.63.0.1
  tcp2_conn_port: 31423
  tunnel_device:
    name: dpTcpTunClient
    ip: 192.170.10.10
    routePrefix: 16

logger:
  level: info
